-- Initialize Aviation database with Airplane and Flight tables
-- This script runs as SYSTEM user and creates the AVIATION schema

-- Switch to the pluggable database (required for Oracle Free multitenant architecture)
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create a tablespace for AVIATION data (Oracle Free lite may not have USERS tablespace)
CREATE TABLESPACE AVIATION_DATA 
  DATAFILE 'aviation_data01.dbf' 
  SIZE 100M 
  AUTOEXTEND ON 
  NEXT 10M 
  MAXSIZE 500M;

-- Create AVIATION user (schema)
CREATE USER AVIATION IDENTIFIED BY "Aviation!Passw0rd"
  DEFAULT TABLESPACE AVIATION_DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON AVIATION_DATA;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO AVIATION;
GRANT CREATE SESSION TO AVIATION;
GRANT CREATE TABLE TO AVIATION;
GRANT CREATE VIEW TO AVIATION;
GRANT CREATE SEQUENCE TO AVIATION;

-- Switch to AVIATION schema context
ALTER SESSION SET CURRENT_SCHEMA = AVIATION;

-- Create Airplane table
CREATE TABLE AVIATION.AIRPLANE (
  AIRPLANE_ID NUMBER(10) PRIMARY KEY,
  REGISTRATION VARCHAR2(20) NOT NULL UNIQUE,
  MODEL VARCHAR2(100) NOT NULL,
  MANUFACTURER VARCHAR2(100) NOT NULL,
  CAPACITY NUMBER(5) NOT NULL,
  YEAR_BUILT NUMBER(4)
);

-- Create Flight table
CREATE TABLE AVIATION.FLIGHT (
  FLIGHT_ID NUMBER(10) PRIMARY KEY,
  FLIGHT_NUMBER VARCHAR2(20) NOT NULL,
  AIRPLANE_ID NUMBER(10) NOT NULL,
  DEPARTURE_AIRPORT VARCHAR2(10) NOT NULL,
  ARRIVAL_AIRPORT VARCHAR2(10) NOT NULL,
  DEPARTURE_TIME TIMESTAMP NOT NULL,
  ARRIVAL_TIME TIMESTAMP NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  CONSTRAINT FK_FLIGHT_AIRPLANE FOREIGN KEY (AIRPLANE_ID) REFERENCES AVIATION.AIRPLANE(AIRPLANE_ID)
);

-- Create sequences for auto-increment
CREATE SEQUENCE AVIATION.AIRPLANE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AVIATION.FLIGHT_SEQ START WITH 1 INCREMENT BY 1;

-- Insert sample airplane data
INSERT INTO AVIATION.AIRPLANE (AIRPLANE_ID, REGISTRATION, MODEL, MANUFACTURER, CAPACITY, YEAR_BUILT)
VALUES (AVIATION.AIRPLANE_SEQ.NEXTVAL, 'N12345', 'Boeing 737-800', 'Boeing', 189, 2015);

INSERT INTO AVIATION.AIRPLANE (AIRPLANE_ID, REGISTRATION, MODEL, MANUFACTURER, CAPACITY, YEAR_BUILT)
VALUES (AVIATION.AIRPLANE_SEQ.NEXTVAL, 'N67890', 'Airbus A320', 'Airbus', 180, 2018);

INSERT INTO AVIATION.AIRPLANE (AIRPLANE_ID, REGISTRATION, MODEL, MANUFACTURER, CAPACITY, YEAR_BUILT)
VALUES (AVIATION.AIRPLANE_SEQ.NEXTVAL, 'N24680', 'Boeing 787-9', 'Boeing', 296, 2020);

INSERT INTO AVIATION.AIRPLANE (AIRPLANE_ID, REGISTRATION, MODEL, MANUFACTURER, CAPACITY, YEAR_BUILT)
VALUES (AVIATION.AIRPLANE_SEQ.NEXTVAL, 'N13579', 'Airbus A350-900', 'Airbus', 315, 2021);

-- Insert sample flight data
INSERT INTO AVIATION.FLIGHT (FLIGHT_ID, FLIGHT_NUMBER, AIRPLANE_ID, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, STATUS)
VALUES (AVIATION.FLIGHT_SEQ.NEXTVAL, 'AA101', 1, 'JFK', 'LAX', TIMESTAMP '2024-03-15 08:00:00', TIMESTAMP '2024-03-15 11:30:00', 'COMPLETED');

INSERT INTO AVIATION.FLIGHT (FLIGHT_ID, FLIGHT_NUMBER, AIRPLANE_ID, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, STATUS)
VALUES (AVIATION.FLIGHT_SEQ.NEXTVAL, 'UA202', 2, 'ORD', 'SFO', TIMESTAMP '2024-03-15 09:15:00', TIMESTAMP '2024-03-15 11:45:00', 'COMPLETED');

INSERT INTO AVIATION.FLIGHT (FLIGHT_ID, FLIGHT_NUMBER, AIRPLANE_ID, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, STATUS)
VALUES (AVIATION.FLIGHT_SEQ.NEXTVAL, 'DL303', 3, 'ATL', 'SEA', TIMESTAMP '2024-03-15 10:30:00', TIMESTAMP '2024-03-15 13:00:00', 'ON_TIME');

INSERT INTO AVIATION.FLIGHT (FLIGHT_ID, FLIGHT_NUMBER, AIRPLANE_ID, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, STATUS)
VALUES (AVIATION.FLIGHT_SEQ.NEXTVAL, 'SW404', 1, 'DAL', 'DEN', TIMESTAMP '2024-03-15 14:00:00', TIMESTAMP '2024-03-15 15:45:00', 'BOARDING');

INSERT INTO AVIATION.FLIGHT (FLIGHT_ID, FLIGHT_NUMBER, AIRPLANE_ID, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, STATUS)
VALUES (AVIATION.FLIGHT_SEQ.NEXTVAL, 'BA505', 4, 'LHR', 'JFK', TIMESTAMP '2024-03-15 16:00:00', TIMESTAMP '2024-03-15 19:30:00', 'SCHEDULED');

COMMIT;

-- Display confirmation
SELECT 'Aviation database initialized successfully' AS STATUS FROM DUAL;
SELECT COUNT(*) AS AIRPLANE_COUNT FROM AVIATION.AIRPLANE;
SELECT COUNT(*) AS FLIGHT_COUNT FROM AVIATION.FLIGHT;
